### ISSUE TITLE
[Request]:  pops & bangs

### ISSUE THREAD

**Issue by Beginner555989** [Deadlineem/Extras_Addon#129]
### Request

bro this feature is awsome .. thank you so much for it . can u make it other players see it and hear it ?
![122](https://github.com/user-attachments/assets/5a11c808-93a2-47a0-8f07-21b0116ed742)

**Comment by xesdoog** [comment]
> @xesdoog this may be doable.

The sound is already synced. All players near your vehicle can hear it as long as they're not blocking it with a menu (it triggers a sound spam protection but it's not a toxic feature).
As for PTFX, the only way is to find a different particle effect that is synced online. I've opened a discussion in YimMenu about this exact thing.

**Comment by Deadlineem** [comment]
> > @xesdoog this may be doable.
> 
> The sound is already synced. All players near your vehicle can hear it as long as they're not blocking it with a menu (it triggers a sound spam protection but it's not a toxic feature). As for PTFX, the only way is to find a different particle effect that is synced online. I've opened a discussion in YimMenu about this exact thing.

That got me wondering.  what about the thruster ptfx for mk1/jet/voltic/vigilante OR the boost flames from the arena war monster truck?  They are networked are they not?

**Comment by xesdoog** [comment]
> That got me wondering.  what about the thruster ptfx for mk1/jet/voltic/vigilante OR the boost flames from the arena war monster truck?  They are networked/synced are they not?

Yeah we need to hop in a session and try different PTFX. I can write something that cycles through a list of particles to make things easier.
