### ISSUE TITLE
[Bug]: tire PTFX is not working 

### ISSUE THREAD

**Issue by Beginner555989** [Deadlineem/Extras_Addon#142]
### Description

![Screenshot 2024-12-07 032544](https://github.com/user-attachments/assets/65c78491-1b70-4d66-8394-72d3a92c62c2)

### Steps to Reproduce

i know not that importint but i like it 

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
> ### Description
> 
> ![Screenshot 2024-12-07 032544](https://private-user-images.githubusercontent.com/173267641/393464507-65c78491-1b70-4d66-8394-72d3a92c62c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Mzk3NTIsIm5iZiI6MTczMzUzOTQ1MiwicGF0aCI6Ii8xNzMyNjc2NDEvMzkzNDY0NTA3LTY1Yzc4NDkxLTFiNzAtNGQ2Ni04Mzk0LTcyZDNhOTJjNjJjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwMjQ0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWMxNzA1MWMzNjNlZDA5YmQxMDA2ZjU0MTMyZjBhMWY4OWFkOGQxNDk5NmFmNDYxMjJlZTM2MzA2MjJkMjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nBA3v2Chbs8V-c_Mt2RRZKlSwJmrt2ou0S57w5SC5wA)
> ### Steps to Reproduce
> 
> i know not that importint but i like it
> ### Screenshots
> 
> _No response_
> ### Additional Information
> 
> _No response_
> ### Version
> 
>     * [x]  I've confirmed the issue exists on the latest version

When trying to use this, does the console show any errors on it?  If so could you share your cout.log?

**Comment by Deadlineem** [comment]
PTFX should work now
