### ISSUE TITLE
[Bug]: function for drop money or RP does not work (target/global)

### ISSUE THREAD

**Issue by wei9htlessness** [Deadlineem/Extras_Addon#144]
### Description

function for drop money or RP does not work (target/global)
figure drop works
last version 1.70 / 3411

### Steps to Reproduce

...

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
> ### Description
> function for drop money or RP does not work (target/global) figure drop works last version 1.70 / 3411
> 
> ### Steps to Reproduce
> ...
> 
> ### Screenshots
> _No response_
> 
> ### Additional Information
> _No response_
> 
> ### Version
> * [x]  I've confirmed the issue exists on the latest version

This is known, R* patched using this RP method on others with 1.70 and it can only be done on yourself now.
